services:
  frontend:
    build:
      context: ./frontend
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"

    container_name: tcc-frontend
    working_dir: /workdir

    environment:
      HOME: /tmp
      npm_config_cache: /tmp/.npm

    command: >
      sh -c "
        npm install &&
        npx concurrently '
          ionic serve --host=0.0.0.0 --port=8100
        ' '
          ng serve --host=0.0.0.0 --port=4200 --disable-host-check
        ' '
          npx chokidar dist -c \"echo Syncing && npx cap copy\"
        '
      "

    volumes:
      - ./frontend/tcc:/workdir

    ports:
      - "80:4200"
      - "8100:8100"

  clientes:
    image: maven:3.8.4-openjdk-17-slim
    depends_on:
     - postgres
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Dspring.devtools.restart.enabled=true -Dspring-boot.run.profiles=dev'"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/TCC
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=senha
      - MAVEN_CONFIG=/tmp/.m2
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend/clientes_TCC/:/app
      - ~/.m2:/tmp/.m2
    ports:
      - 8080:8080

  ms-dashboard:
    build: ./backend/ms-dashboard
    ports:
      - 8085:8085
    volumes:
      - ./backend/ms-dashboard:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8085
    environment:
      - DATABASE_URL=postgresql://postgres:senha@postgres:5432/TCC
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - postgres

  api-gateway:
    image: node:22-alpine
    container_name: tcc-gateway
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npx tsx watch server.ts
      "
    volumes:
      - ./backend/api-gateway:/app
    ports:
      - "3000:3000"
    environment:
      GATEWAY_PORT: 3000
      BI_MS_URL: http://ms-dashboard:8085
      BUSINESS_MS_URL: http://clientes:8080
      CORS_ORIGINS: http://localhost:4200,http://localhost:8100
    depends_on:
      - ms-dashboard
      - clientes

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: TCC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - ./bancosDeDados/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - tcc_net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - tcc_net

volumes:
  pgadmin_data:

networks:
  tcc_net:
    driver: bridge