services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - api-gateway

  api-gateway:
    command: >
      sh -c "
        npm install &&
        npx tsx server.ts
      "
    environment:
      CORS_ORIGINS: "https://app.curitibativa.online,capacitor://localhost,http://localhost"

  ms-java:
    command: "mvn spring-boot:run -Dspring-boot.run.jvmArguments='-Dspring-boot.run.profiles=prod'"
