export enum TipoProposicao {
    PROJETO_DE_LEI = 'PROJETO_DE_LEI',
    REQUERIMENTO = 'REQUERIMENTO',
    INDICACAO = 'INDICACAO',
    EMENDA = 'EMENDA',
    MOcaO = 'MOÇÃO',
    PEDIDO_DE_INFORMACAO = 'PEDIDO_DE_INFORMACAO',
}
